**TensorFlow**

In [1]:
# Basic Setup
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

*Initialization of Tensors*

Manual Initialization

In [3]:
x = tf.constant(5) # Integer
print(x)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
x = tf.constant(5.0) # Float
print(x)

tf.Tensor(5.0, shape=(), dtype=float32)


In [5]:
x = tf.constant(5, shape=(1,1), dtype=tf.float32) # We can specify shape and dtype as well
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)


In [6]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Other Initialization Methods

In [7]:
x = tf.ones((4,4))
print(x)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [8]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
x = tf.eye(5) # Identity Matrix
print(x)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [11]:
# Normal Distribution
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 1.4092216   0.62743026  1.3880677 ]
 [-1.1399809   0.61785513 -2.0693035 ]
 [ 0.6092591   1.1849921   0.17982979]], shape=(3, 3), dtype=float32)


In [14]:
# Uniform Distribution
x = tf.random.uniform((2,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.53055334 0.7808393  0.8700541 ]
 [0.9092783  0.15189981 0.6457126 ]], shape=(2, 3), dtype=float32)
