# TensorFlow

In [1]:
# Basic Setup
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf

In [2]:
# In case of GPU alloting a lot of memory, you can use the following:
# physical_devices = tf.config.list_physical_devices('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[0], true)

**Initialization of Tensors**

Manual Initialization

In [3]:
x = tf.constant(5) # Integer
print(x)

tf.Tensor(5, shape=(), dtype=int32)


In [4]:
x = tf.constant(5.0) # Float
print(x)

tf.Tensor(5.0, shape=(), dtype=float32)


In [5]:
x = tf.constant(5, shape=(1,1), dtype=tf.float32) # We can specify shape and dtype as well
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)


In [6]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Other Initialization Methods

In [7]:
x = tf.ones((4,4))
print(x)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [8]:
x = tf.zeros((3,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.eye(5) # Identity Matrix
print(x)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [10]:
# Normal Distribution
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.7234548   0.9770678  -0.14010085]
 [ 0.22211835 -0.19474901 -1.0401582 ]
 [ 1.4525579   0.25438014  0.9305625 ]], shape=(3, 3), dtype=float32)


In [11]:
# Uniform Distribution
x = tf.random.uniform((2,3), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.6426308  0.11376595 0.5990875 ]
 [0.35113883 0.11026728 0.6204461 ]], shape=(2, 3), dtype=float32)


**Using range**

In [12]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [13]:
x = tf.range(start = 1, limit=10, delta = 2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [14]:
x = tf.range(start = 1, limit=10, delta = 2)
x = tf.cast(x, dtype=tf.float64) # To convert
print(x)

# Other methods include tf.float (16,32,64), tf.int (8,16,32,64), tf.bool

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


**Mathematical Operations** 

In [15]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y) # We can also just use z = x + y

print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [16]:
z = tf.subtract(x,y) # z=x-y can also be used
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [17]:
z = tf.divide(x,y) # z = x/y can also be used
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [18]:
z = tf.multiply(x,y) # z = x*y can also be used
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [19]:
z = tf.tensordot(x,y,axes=1) # We would otherwise have to do tf.reduce_sum(x*y, axis =0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [20]:
z = x**5 # Raised to
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [21]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x,y) # z = x@y can be used

print(z)

tf.Tensor(
[[-0.17225756  0.18656898 -0.09706383  0.0212181 ]
 [ 1.167648   -0.8160668   0.45854145 -0.35127348]], shape=(2, 4), dtype=float32)


**Indexing**

In [22]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


In [23]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [24]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [25]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)

**Reshaping**

In [26]:
x = tf.range(9)
print(x)

x = tf.reshape(x,(3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [27]:
x = tf.transpose(x,perm = [1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
